### ISSUE TITLE
Show+Select browser profiles

### ISSUE THREAD

**Issue by cweiske** [properlypurple/braus#18]
I have a private and a work profile in Firefox, but Braus only shows Firefox and Chromium.

I would like to be able to select the Firefox work and Firefox private profile.

**Comment by properlypurple** [comment]
You need to create .desktop files in ~/.local/share/applications for the profiles, and then they will be shown. Braus uses GLib to pick up browsers from the system, and the desktop files are the best way to set that up.

**Comment by cweiske** [comment]
The `.desktop` file needs a `MimeType=` line with `x-scheme-handler/https` in it:
```
[Desktop Entry]
Version=1.1
Type=Application
Name=FIrefox Company
Icon=firefox-symbolic
Exec=/home/cweiske/bin/firefox-company
Actions=
Categories=WebBrowser;X-GNOME-WebApplications;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;application/x-xpinstall;
```

After creating/modifying this desktop file, braus does not yet see it. The desktop file cache must be updated at first:

```
$ update-desktop-database  ~/.local/share/applications/
```

Now it is visible in braus.
