### ISSUE TITLE
Run src without installation?

### ISSUE THREAD

**Issue by cweiske** [properlypurple/braus#22]
During development, how can I run braus directly from the src/ directory without installing it?

**Comment by properlypurple** [comment]
I have not tried this since switching to meson, but you should be able to do this

````
meson build --prefix=(pwd)/builddir/
ninja -C build
ninja -C build install
GSETTINGS_SCHEMA_DIR=builddir/share/glib-2.0/schemas ./builddir/bin/braus
````

**Comment by properlypurple** [comment]
You might want to switch `(pwd)` with `$(pwd)` for bash and zsh. I use fish so this works for me.

**Comment by cweiske** [comment]
That uses the globally installed braus code, not the local checkout.

----

I tried something different that mostly works:
```
$ ln -s src braus
$ cp src/braus.in src/braus
# adjust it
$ python3 src/braus
```

The manual setup is not nice, but it's something workable.

**Comment by properlypurple** [comment]
Try uninstalling the globally installed version when developing, and this should work.

**Comment by cweiske** [comment]
That will work, but is additional hassle.
